// Code generated by ent, DO NOT EDIT.

package accountinfo

const (
	// Label holds the string label denoting the accountinfo type in the database.
	Label = "account_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// Table holds the table name of the accountinfo in the database.
	Table = "account_infos"
)

// Columns holds all SQL columns for accountinfo fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldPassword,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
