// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountInfosColumns holds the columns for the "account_infos" table.
	AccountInfosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
	}
	// AccountInfosTable holds the schema information for the "account_infos" table.
	AccountInfosTable = &schema.Table{
		Name:       "account_infos",
		Columns:    AccountInfosColumns,
		PrimaryKey: []*schema.Column{AccountInfosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountInfosTable,
	}
)

func init() {
}
