// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/accountinfo"
	"main/ent/internal"
	"main/ent/predicate"
	"main/internal/property"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountInfoUpdate is the builder for updating AccountInfo entities.
type AccountInfoUpdate struct {
	config
	hooks     []Hook
	mutation  *AccountInfoMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AccountInfoUpdate builder.
func (aiu *AccountInfoUpdate) Where(ps ...predicate.AccountInfo) *AccountInfoUpdate {
	aiu.mutation.Where(ps...)
	return aiu
}

// SetUsername sets the "username" field.
func (aiu *AccountInfoUpdate) SetUsername(s string) *AccountInfoUpdate {
	aiu.mutation.SetUsername(s)
	return aiu
}

// SetPassword sets the "password" field.
func (aiu *AccountInfoUpdate) SetPassword(pr property.Password) *AccountInfoUpdate {
	aiu.mutation.SetPassword(pr)
	return aiu
}

// Mutation returns the AccountInfoMutation object of the builder.
func (aiu *AccountInfoUpdate) Mutation() *AccountInfoMutation {
	return aiu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aiu *AccountInfoUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(aiu.hooks) == 0 {
		affected, err = aiu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aiu.mutation = mutation
			affected, err = aiu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(aiu.hooks) - 1; i >= 0; i-- {
			if aiu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aiu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aiu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (aiu *AccountInfoUpdate) SaveX(ctx context.Context) int {
	affected, err := aiu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aiu *AccountInfoUpdate) Exec(ctx context.Context) error {
	_, err := aiu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aiu *AccountInfoUpdate) ExecX(ctx context.Context) {
	if err := aiu.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (aiu *AccountInfoUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AccountInfoUpdate {
	aiu.modifiers = append(aiu.modifiers, modifiers...)
	return aiu
}

func (aiu *AccountInfoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   accountinfo.Table,
			Columns: accountinfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: accountinfo.FieldID,
			},
		},
	}
	if ps := aiu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aiu.mutation.Username(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountinfo.FieldUsername,
		})
	}
	if value, ok := aiu.mutation.Password(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountinfo.FieldPassword,
		})
	}
	_spec.Node.Schema = aiu.schemaConfig.AccountInfo
	ctx = internal.NewSchemaConfigContext(ctx, aiu.schemaConfig)
	_spec.Modifiers = aiu.modifiers
	if n, err = sqlgraph.UpdateNodes(ctx, aiu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// AccountInfoUpdateOne is the builder for updating a single AccountInfo entity.
type AccountInfoUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AccountInfoMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUsername sets the "username" field.
func (aiuo *AccountInfoUpdateOne) SetUsername(s string) *AccountInfoUpdateOne {
	aiuo.mutation.SetUsername(s)
	return aiuo
}

// SetPassword sets the "password" field.
func (aiuo *AccountInfoUpdateOne) SetPassword(pr property.Password) *AccountInfoUpdateOne {
	aiuo.mutation.SetPassword(pr)
	return aiuo
}

// Mutation returns the AccountInfoMutation object of the builder.
func (aiuo *AccountInfoUpdateOne) Mutation() *AccountInfoMutation {
	return aiuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aiuo *AccountInfoUpdateOne) Select(field string, fields ...string) *AccountInfoUpdateOne {
	aiuo.fields = append([]string{field}, fields...)
	return aiuo
}

// Save executes the query and returns the updated AccountInfo entity.
func (aiuo *AccountInfoUpdateOne) Save(ctx context.Context) (*AccountInfo, error) {
	var (
		err  error
		node *AccountInfo
	)
	if len(aiuo.hooks) == 0 {
		node, err = aiuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aiuo.mutation = mutation
			node, err = aiuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(aiuo.hooks) - 1; i >= 0; i-- {
			if aiuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aiuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, aiuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*AccountInfo)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AccountInfoMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (aiuo *AccountInfoUpdateOne) SaveX(ctx context.Context) *AccountInfo {
	node, err := aiuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aiuo *AccountInfoUpdateOne) Exec(ctx context.Context) error {
	_, err := aiuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aiuo *AccountInfoUpdateOne) ExecX(ctx context.Context) {
	if err := aiuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (aiuo *AccountInfoUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AccountInfoUpdateOne {
	aiuo.modifiers = append(aiuo.modifiers, modifiers...)
	return aiuo
}

func (aiuo *AccountInfoUpdateOne) sqlSave(ctx context.Context) (_node *AccountInfo, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   accountinfo.Table,
			Columns: accountinfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: accountinfo.FieldID,
			},
		},
	}
	id, ok := aiuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountInfo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aiuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountinfo.FieldID)
		for _, f := range fields {
			if !accountinfo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aiuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aiuo.mutation.Username(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountinfo.FieldUsername,
		})
	}
	if value, ok := aiuo.mutation.Password(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountinfo.FieldPassword,
		})
	}
	_spec.Node.Schema = aiuo.schemaConfig.AccountInfo
	ctx = internal.NewSchemaConfigContext(ctx, aiuo.schemaConfig)
	_spec.Modifiers = aiuo.modifiers
	_node = &AccountInfo{config: aiuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aiuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
