// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/accountinfo"
	"main/internal/property"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountInfoCreate is the builder for creating a AccountInfo entity.
type AccountInfoCreate struct {
	config
	mutation *AccountInfoMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (aic *AccountInfoCreate) SetUsername(s string) *AccountInfoCreate {
	aic.mutation.SetUsername(s)
	return aic
}

// SetPassword sets the "password" field.
func (aic *AccountInfoCreate) SetPassword(pr property.Password) *AccountInfoCreate {
	aic.mutation.SetPassword(pr)
	return aic
}

// Mutation returns the AccountInfoMutation object of the builder.
func (aic *AccountInfoCreate) Mutation() *AccountInfoMutation {
	return aic.mutation
}

// Save creates the AccountInfo in the database.
func (aic *AccountInfoCreate) Save(ctx context.Context) (*AccountInfo, error) {
	var (
		err  error
		node *AccountInfo
	)
	if len(aic.hooks) == 0 {
		if err = aic.check(); err != nil {
			return nil, err
		}
		node, err = aic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = aic.check(); err != nil {
				return nil, err
			}
			aic.mutation = mutation
			if node, err = aic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(aic.hooks) - 1; i >= 0; i-- {
			if aic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aic.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, aic.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*AccountInfo)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AccountInfoMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (aic *AccountInfoCreate) SaveX(ctx context.Context) *AccountInfo {
	v, err := aic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aic *AccountInfoCreate) Exec(ctx context.Context) error {
	_, err := aic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aic *AccountInfoCreate) ExecX(ctx context.Context) {
	if err := aic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aic *AccountInfoCreate) check() error {
	if _, ok := aic.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "AccountInfo.username"`)}
	}
	if _, ok := aic.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "AccountInfo.password"`)}
	}
	return nil
}

func (aic *AccountInfoCreate) sqlSave(ctx context.Context) (*AccountInfo, error) {
	_node, _spec := aic.createSpec()
	if err := sqlgraph.CreateNode(ctx, aic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (aic *AccountInfoCreate) createSpec() (*AccountInfo, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountInfo{config: aic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: accountinfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: accountinfo.FieldID,
			},
		}
	)
	_spec.Schema = aic.schemaConfig.AccountInfo
	if value, ok := aic.mutation.Username(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountinfo.FieldUsername,
		})
		_node.Username = value
	}
	if value, ok := aic.mutation.Password(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountinfo.FieldPassword,
		})
		_node.Password = value
	}
	return _node, _spec
}

// AccountInfoCreateBulk is the builder for creating many AccountInfo entities in bulk.
type AccountInfoCreateBulk struct {
	config
	builders []*AccountInfoCreate
}

// Save creates the AccountInfo entities in the database.
func (aicb *AccountInfoCreateBulk) Save(ctx context.Context) ([]*AccountInfo, error) {
	specs := make([]*sqlgraph.CreateSpec, len(aicb.builders))
	nodes := make([]*AccountInfo, len(aicb.builders))
	mutators := make([]Mutator, len(aicb.builders))
	for i := range aicb.builders {
		func(i int, root context.Context) {
			builder := aicb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountInfoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aicb *AccountInfoCreateBulk) SaveX(ctx context.Context) []*AccountInfo {
	v, err := aicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aicb *AccountInfoCreateBulk) Exec(ctx context.Context) error {
	_, err := aicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aicb *AccountInfoCreateBulk) ExecX(ctx context.Context) {
	if err := aicb.Exec(ctx); err != nil {
		panic(err)
	}
}
