// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccountInfo is the predicate function for accountinfo builders.
type AccountInfo func(*sql.Selector)
